[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.normal]
family = "Noto Sans Mono"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
