#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

export XIM="fcitx"
export XIM_PROGRAM="fcitx"
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE=$XIM
export QT_IM_MODULE=$XIM
export BROWSER="firefox"
export export GTK2_RC_FILE="$HOME/.gtkrc-2.0"


alias mpv='mpv --stop-screensaver'


if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

wmname LG3D &
nm-applet --sm-disable &
#urxvtd&
#udiskie -s&
#cbatticon&
#xbindkeys
#nm-applet&
unclutter -idle 1&
parcellite -n&
fcitx&
# sogou-qimpanel&
# compton -cGb -o 1 -r 7 -l -10 -t -10 --backend glx --paint-on-overlay --vsync opengl-swc --shadow-exclude fullscreen &
exec awesome -c ~/.config/awesome/new.lua -a
# exec i3
# exec awesome
