[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
# brew install font-dejavu-sans-mono-nerd-font
family = "DejaVuSansM Nerd Font"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
